### ISSUE TITLE
Commenting capabilities

### ISSUE THREAD

**Issue by AtomicNess123** [LaurenceWarne/ox-yaow.el#1]
Does this allow for comments like DISQUS?

**Comment by LaurenceWarne** [comment]
Interesting, I think something like this is possible in vanilla org mode, I was playing around this morning with it based on this link: http://snarvaez.poweredbygnulinux.com/notes/org-mode-publishing-adding-disqus-code.html, I was able to integrate it:

![ox-yaow-disqus](https://user-images.githubusercontent.com/17688577/124921472-59670180-dff0-11eb-9dd1-7b3d6da9814f.png)

Here's a [link](https://github.com/LaurenceWarne/.emacs.d/blob/4332786614777120a5c59f7ad3f782be09cbbd63/lisp/package-init.el#L122) to the config I used, I then just added:

```elisp
#+BEGIN_EXPORT html
<div id="disqus_thread"></div>
<script>
(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = '{{page_embed}}';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
#+END_EXPORT
```
To the org file I wanted (probably can be automated for all files somehow).

So there is no specific integration provided by `ox-yaow` to answer your original question, but hopefully the above is helpful to you if you were not already aware of it (:

**Comment by AtomicNess123** [comment]
You're very very appreciated, thank you so much! <3

**Comment by LaurenceWarne** [comment]
No problem!

**Comment by AtomicNess123** [comment]
BTW, one last thing, how according to you does ELEVENTY compare to just using org? I haven't decided what to base my blog on yet. Maybe you have written about it elsewhere? Thanks.

**Comment by LaurenceWarne** [comment]
> BTW, one last thing, how according to you does ELEVENTY compare to just using org? 

I haven't used it so I can't comment (:
> I haven't decided what to base my blog on yet.

For org blogging I'd recommend something like: https://github.com/ardumont/org2jekyll, the author has drawn up some comparisons with other blogging tools there also.

**Comment by AtomicNess123** [comment]
Excellent, thank you! Is org2jekyll similar to Hugo?

**Comment by LaurenceWarne** [comment]
> Excellent, thank you! Is org2jekyll similar to Hugo?

I don't know, I haven't used Hugo (:
