### ISSUE TITLE
export static assets (e.g. images/sound/etc.)

### ISSUE THREAD

**Issue by zwessels** [LaurenceWarne/ox-yaow.el#2]
how can one configure this to also export images/audio/etc. to the generated html site?

e.g.

```
* Hello
[[file:img/world.jpg]]
```

i know for `ox-publish` one would do something like:

```
("org-static"
 :base-directory "~/org/"
 :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
 :publishing-directory "~/public_html/"
 :recursive t
 :publishing-function org-publish-attachment
 )
```

**Comment by LaurenceWarne** [comment]
I wasn't using any static on my site so I'd overlooked this a bit :slightly_smiling_face:, but what you have should work fine: https://laurencewarne.github.io/wiki/wiki.html.

I've updated the README with an example project using static, let me know if that works for you.

**Comment by zwessels** [comment]
perfect, thanks :)
